// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pulumirpc.analyzer

/** AnalyzerResource defines the view of a Pulumi-managed resource as sent to Analyzers. The properties
  * of the resource are specific to the type of analysis being performed. See the Analyzer
  * service definition for more information.
  *
  * @param type
  *   the type token of the resource.
  * @param properties
  *   the full properties to use for validation.
  * @param urn
  *   the URN of the resource.
  * @param name
  *   the name for the resource's URN.
  * @param options
  *   the resource options.
  * @param provider
  *   the resource's provider.
  * @param parent
  *   an optional parent URN that this child resource belongs to.
  * @param dependencies
  *   a list of URNs that this resource depends on.
  * @param propertyDependencies
  *   a map from property keys to the dependencies of the property.
  */
@SerialVersionUID(0L)
final case class AnalyzerResource(
    `type`: _root_.scala.Predef.String = "",
    properties: _root_.scala.Option[com.google.protobuf.struct.Struct] = _root_.scala.None,
    urn: _root_.scala.Predef.String = "",
    name: _root_.scala.Predef.String = "",
    options: _root_.scala.Option[pulumirpc.analyzer.AnalyzerResourceOptions] = _root_.scala.None,
    provider: _root_.scala.Option[pulumirpc.analyzer.AnalyzerProviderResource] = _root_.scala.None,
    parent: _root_.scala.Predef.String = "",
    dependencies: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    propertyDependencies: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies] = _root_.scala.collection.immutable.Map.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[AnalyzerResource] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = `type`
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (properties.isDefined) {
        val __value = properties.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = urn
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      if (options.isDefined) {
        val __value = options.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (provider.isDefined) {
        val __value = provider.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = parent
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      dependencies.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(8, __value)
      }
      propertyDependencies.foreach { __item =>
        val __value = pulumirpc.analyzer.AnalyzerResource._typemapper_propertyDependencies.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = `type`
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      properties.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = urn
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      options.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      provider.foreach { __v =>
        val __m = __v
        _output__.writeTag(6, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = parent
        if (!__v.isEmpty) {
          _output__.writeString(7, __v)
        }
      };
      dependencies.foreach { __v =>
        val __m = __v
        _output__.writeString(8, __m)
      };
      propertyDependencies.foreach { __v =>
        val __m = pulumirpc.analyzer.AnalyzerResource._typemapper_propertyDependencies.toBase(__v)
        _output__.writeTag(9, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withType(__v: _root_.scala.Predef.String): AnalyzerResource = copy(`type` = __v)
    def getProperties: com.google.protobuf.struct.Struct = properties.getOrElse(com.google.protobuf.struct.Struct.defaultInstance)
    def clearProperties: AnalyzerResource = copy(properties = _root_.scala.None)
    def withProperties(__v: com.google.protobuf.struct.Struct): AnalyzerResource = copy(properties = Option(__v))
    def withUrn(__v: _root_.scala.Predef.String): AnalyzerResource = copy(urn = __v)
    def withName(__v: _root_.scala.Predef.String): AnalyzerResource = copy(name = __v)
    def getOptions: pulumirpc.analyzer.AnalyzerResourceOptions = options.getOrElse(pulumirpc.analyzer.AnalyzerResourceOptions.defaultInstance)
    def clearOptions: AnalyzerResource = copy(options = _root_.scala.None)
    def withOptions(__v: pulumirpc.analyzer.AnalyzerResourceOptions): AnalyzerResource = copy(options = Option(__v))
    def getProvider: pulumirpc.analyzer.AnalyzerProviderResource = provider.getOrElse(pulumirpc.analyzer.AnalyzerProviderResource.defaultInstance)
    def clearProvider: AnalyzerResource = copy(provider = _root_.scala.None)
    def withProvider(__v: pulumirpc.analyzer.AnalyzerProviderResource): AnalyzerResource = copy(provider = Option(__v))
    def withParent(__v: _root_.scala.Predef.String): AnalyzerResource = copy(parent = __v)
    def clearDependencies = copy(dependencies = _root_.scala.Seq.empty)
    def addDependencies(__vs: _root_.scala.Predef.String *): AnalyzerResource = addAllDependencies(__vs)
    def addAllDependencies(__vs: Iterable[_root_.scala.Predef.String]): AnalyzerResource = copy(dependencies = dependencies ++ __vs)
    def withDependencies(__v: _root_.scala.Seq[_root_.scala.Predef.String]): AnalyzerResource = copy(dependencies = __v)
    def clearPropertyDependencies = copy(propertyDependencies = _root_.scala.collection.immutable.Map.empty)
    def addPropertyDependencies(__vs: (_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies) *): AnalyzerResource = addAllPropertyDependencies(__vs)
    def addAllPropertyDependencies(__vs: Iterable[(_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies)]): AnalyzerResource = copy(propertyDependencies = propertyDependencies ++ __vs)
    def withPropertyDependencies(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies]): AnalyzerResource = copy(propertyDependencies = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = `type`
          if (__t != "") __t else null
        }
        case 2 => properties.orNull
        case 3 => {
          val __t = urn
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 5 => options.orNull
        case 6 => provider.orNull
        case 7 => {
          val __t = parent
          if (__t != "") __t else null
        }
        case 8 => dependencies
        case 9 => propertyDependencies.iterator.map(pulumirpc.analyzer.AnalyzerResource._typemapper_propertyDependencies.toBase(_)).toSeq
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(`type`)
        case 2 => properties.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => _root_.scalapb.descriptors.PString(urn)
        case 4 => _root_.scalapb.descriptors.PString(name)
        case 5 => options.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 6 => provider.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 7 => _root_.scalapb.descriptors.PString(parent)
        case 8 => _root_.scalapb.descriptors.PRepeated(dependencies.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
        case 9 => _root_.scalapb.descriptors.PRepeated(propertyDependencies.iterator.map(pulumirpc.analyzer.AnalyzerResource._typemapper_propertyDependencies.toBase(_).toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: pulumirpc.analyzer.AnalyzerResource.type = pulumirpc.analyzer.AnalyzerResource
    // @@protoc_insertion_point(GeneratedMessage[pulumirpc.AnalyzerResource])
}

object AnalyzerResource extends scalapb.GeneratedMessageCompanion[pulumirpc.analyzer.AnalyzerResource] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.analyzer.AnalyzerResource] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.analyzer.AnalyzerResource = {
    var __type: _root_.scala.Predef.String = ""
    var __properties: _root_.scala.Option[com.google.protobuf.struct.Struct] = _root_.scala.None
    var __urn: _root_.scala.Predef.String = ""
    var __name: _root_.scala.Predef.String = ""
    var __options: _root_.scala.Option[pulumirpc.analyzer.AnalyzerResourceOptions] = _root_.scala.None
    var __provider: _root_.scala.Option[pulumirpc.analyzer.AnalyzerProviderResource] = _root_.scala.None
    var __parent: _root_.scala.Predef.String = ""
    val __dependencies: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    val __propertyDependencies: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __type = _input__.readStringRequireUtf8()
        case 18 =>
          __properties = Option(__properties.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.struct.Struct](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __urn = _input__.readStringRequireUtf8()
        case 34 =>
          __name = _input__.readStringRequireUtf8()
        case 42 =>
          __options = Option(__options.fold(_root_.scalapb.LiteParser.readMessage[pulumirpc.analyzer.AnalyzerResourceOptions](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 50 =>
          __provider = Option(__provider.fold(_root_.scalapb.LiteParser.readMessage[pulumirpc.analyzer.AnalyzerProviderResource](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 58 =>
          __parent = _input__.readStringRequireUtf8()
        case 66 =>
          __dependencies += _input__.readStringRequireUtf8()
        case 74 =>
          __propertyDependencies += pulumirpc.analyzer.AnalyzerResource._typemapper_propertyDependencies.toCustom(_root_.scalapb.LiteParser.readMessage[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry](_input__))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    pulumirpc.analyzer.AnalyzerResource(
        `type` = __type,
        properties = __properties,
        urn = __urn,
        name = __name,
        options = __options,
        provider = __provider,
        parent = __parent,
        dependencies = __dependencies.result(),
        propertyDependencies = __propertyDependencies.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.analyzer.AnalyzerResource] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      pulumirpc.analyzer.AnalyzerResource(
        `type` = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        properties = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.struct.Struct]]),
        urn = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        options = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[_root_.scala.Option[pulumirpc.analyzer.AnalyzerResourceOptions]]),
        provider = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).flatMap(_.as[_root_.scala.Option[pulumirpc.analyzer.AnalyzerProviderResource]]),
        parent = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        dependencies = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        propertyDependencies = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Seq[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(pulumirpc.analyzer.AnalyzerResource._typemapper_propertyDependencies.toCustom(_)).toMap
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AnalyzerProto.javaDescriptor.getMessageTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AnalyzerProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = com.google.protobuf.struct.Struct
      case 5 => __out = pulumirpc.analyzer.AnalyzerResourceOptions
      case 6 => __out = pulumirpc.analyzer.AnalyzerProviderResource
      case 9 => __out = pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = pulumirpc.analyzer.AnalyzerResource(
    `type` = "",
    properties = _root_.scala.None,
    urn = "",
    name = "",
    options = _root_.scala.None,
    provider = _root_.scala.None,
    parent = "",
    dependencies = _root_.scala.Seq.empty,
    propertyDependencies = _root_.scala.collection.immutable.Map.empty
  )
  @SerialVersionUID(0L)
  final case class PropertyDependenciesEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.scala.Option[pulumirpc.analyzer.AnalyzerPropertyDependencies] = _root_.scala.None,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[PropertyDependenciesEntry] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        if (value.isDefined) {
          val __value = value.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          val __m = __v
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        unknownFields.writeTo(_output__)
      }
      def withKey(__v: _root_.scala.Predef.String): PropertyDependenciesEntry = copy(key = __v)
      def getValue: pulumirpc.analyzer.AnalyzerPropertyDependencies = value.getOrElse(pulumirpc.analyzer.AnalyzerPropertyDependencies.defaultInstance)
      def clearValue: PropertyDependenciesEntry = copy(value = _root_.scala.None)
      def withValue(__v: pulumirpc.analyzer.AnalyzerPropertyDependencies): PropertyDependenciesEntry = copy(value = Option(__v))
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry.type = pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry
      // @@protoc_insertion_point(GeneratedMessage[pulumirpc.AnalyzerResource.PropertyDependenciesEntry])
  }
  
  object PropertyDependenciesEntry extends scalapb.GeneratedMessageCompanion[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.scala.Option[pulumirpc.analyzer.AnalyzerPropertyDependencies] = _root_.scala.None
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = Option(__value.fold(_root_.scalapb.LiteParser.readMessage[pulumirpc.analyzer.AnalyzerPropertyDependencies](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry(
          key = __key,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[pulumirpc.analyzer.AnalyzerPropertyDependencies]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = pulumirpc.analyzer.AnalyzerResource.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = pulumirpc.analyzer.AnalyzerResource.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = pulumirpc.analyzer.AnalyzerPropertyDependencies
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry(
      key = "",
      value = _root_.scala.None
    )
    implicit class PropertyDependenciesEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.analyzer.AnalyzerPropertyDependencies] = field(_.getValue)((c_, f_) => c_.copy(value = Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[pulumirpc.analyzer.AnalyzerPropertyDependencies]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry, (_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies)] =
      _root_.scalapb.TypeMapper[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry, (_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies)](__m => (__m.key, __m.getValue))(__p => pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry(__p._1, Some(__p._2)))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.scala.Option[pulumirpc.analyzer.AnalyzerPropertyDependencies]
    ): _root_.pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry = _root_.pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.AnalyzerResource.PropertyDependenciesEntry])
  }
  
  implicit class AnalyzerResourceLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.analyzer.AnalyzerResource]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, pulumirpc.analyzer.AnalyzerResource](_l) {
    def `type`: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
    def properties: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.struct.Struct] = field(_.getProperties)((c_, f_) => c_.copy(properties = Option(f_)))
    def optionalProperties: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.struct.Struct]] = field(_.properties)((c_, f_) => c_.copy(properties = f_))
    def urn: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.urn)((c_, f_) => c_.copy(urn = f_))
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def options: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.analyzer.AnalyzerResourceOptions] = field(_.getOptions)((c_, f_) => c_.copy(options = Option(f_)))
    def optionalOptions: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[pulumirpc.analyzer.AnalyzerResourceOptions]] = field(_.options)((c_, f_) => c_.copy(options = f_))
    def provider: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.analyzer.AnalyzerProviderResource] = field(_.getProvider)((c_, f_) => c_.copy(provider = Option(f_)))
    def optionalProvider: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[pulumirpc.analyzer.AnalyzerProviderResource]] = field(_.provider)((c_, f_) => c_.copy(provider = f_))
    def parent: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.parent)((c_, f_) => c_.copy(parent = f_))
    def dependencies: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.dependencies)((c_, f_) => c_.copy(dependencies = f_))
    def propertyDependencies: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies]] = field(_.propertyDependencies)((c_, f_) => c_.copy(propertyDependencies = f_))
  }
  final val TYPE_FIELD_NUMBER = 1
  final val PROPERTIES_FIELD_NUMBER = 2
  final val URN_FIELD_NUMBER = 3
  final val NAME_FIELD_NUMBER = 4
  final val OPTIONS_FIELD_NUMBER = 5
  final val PROVIDER_FIELD_NUMBER = 6
  final val PARENT_FIELD_NUMBER = 7
  final val DEPENDENCIES_FIELD_NUMBER = 8
  final val PROPERTYDEPENDENCIES_FIELD_NUMBER = 9
  @transient
  private[analyzer] val _typemapper_propertyDependencies: _root_.scalapb.TypeMapper[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry, (_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies)] = implicitly[_root_.scalapb.TypeMapper[pulumirpc.analyzer.AnalyzerResource.PropertyDependenciesEntry, (_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies)]]
  def of(
    `type`: _root_.scala.Predef.String,
    properties: _root_.scala.Option[com.google.protobuf.struct.Struct],
    urn: _root_.scala.Predef.String,
    name: _root_.scala.Predef.String,
    options: _root_.scala.Option[pulumirpc.analyzer.AnalyzerResourceOptions],
    provider: _root_.scala.Option[pulumirpc.analyzer.AnalyzerProviderResource],
    parent: _root_.scala.Predef.String,
    dependencies: _root_.scala.Seq[_root_.scala.Predef.String],
    propertyDependencies: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.analyzer.AnalyzerPropertyDependencies]
  ): _root_.pulumirpc.analyzer.AnalyzerResource = _root_.pulumirpc.analyzer.AnalyzerResource(
    `type`,
    properties,
    urn,
    name,
    options,
    provider,
    parent,
    dependencies,
    propertyDependencies
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.AnalyzerResource])
}
