// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pulumirpc.provider

/** @param tok
  *   the function token to invoke.
  * @param args
  *   the arguments for the function invocation.
  * @param argDependencies
  *   a map from argument keys to the dependencies of the argument.
  * @param provider
  *   an optional reference to the provider to use for this invoke.
  * @param version
  *   the version of the provider to use when servicing this request.
  * @param pluginDownloadURL
  *   the pluginDownloadURL of the provider to use when servicing this request.
  * @param pluginChecksums
  *   a map of checksums of the provider to use when servicing this request.
  * @param project
  *   the project name.
  * @param stack
  *   the name of the stack being deployed into.
  * @param config
  *   the configuration variables to apply before running.
  * @param configSecretKeys
  *   the configuration keys that have secret values.
  * @param dryRun
  *   true if we're only doing a dryrun (preview).
  * @param parallel
  *   the degree of parallelism for resource operations (&lt;=1 for serial).
  * @param monitorEndpoint
  *   the address for communicating back to the resource monitor.
  * @param organization
  *   the organization of the stack being deployed into.
  * @param sourcePosition
  *   the optional source position of the user code that initiated the call.
  */
@SerialVersionUID(0L)
final case class CallRequest(
    tok: _root_.scala.Predef.String = "",
    args: _root_.scala.Option[com.google.protobuf.struct.Struct] = _root_.scala.None,
    argDependencies: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies] = _root_.scala.collection.immutable.Map.empty,
    provider: _root_.scala.Predef.String = "",
    version: _root_.scala.Predef.String = "",
    pluginDownloadURL: _root_.scala.Predef.String = "",
    pluginChecksums: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString] = _root_.scala.collection.immutable.Map.empty,
    project: _root_.scala.Predef.String = "",
    stack: _root_.scala.Predef.String = "",
    config: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.scala.Predef.String] = _root_.scala.collection.immutable.Map.empty,
    configSecretKeys: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    dryRun: _root_.scala.Boolean = false,
    parallel: _root_.scala.Int = 0,
    monitorEndpoint: _root_.scala.Predef.String = "",
    organization: _root_.scala.Predef.String = "",
    sourcePosition: _root_.scala.Option[pulumirpc.source.SourcePosition] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[CallRequest] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = tok
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (args.isDefined) {
        val __value = args.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      argDependencies.foreach { __item =>
        val __value = pulumirpc.provider.CallRequest._typemapper_argDependencies.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = provider
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = version
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      
      {
        val __value = pluginDownloadURL
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(13, __value)
        }
      };
      pluginChecksums.foreach { __item =>
        val __value = pulumirpc.provider.CallRequest._typemapper_pluginChecksums.toBase(__item)
        __size += 2 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = project
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      
      {
        val __value = stack
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      config.foreach { __item =>
        val __value = pulumirpc.provider.CallRequest._typemapper_config.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      configSecretKeys.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(9, __value)
      }
      
      {
        val __value = dryRun
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(10, __value)
        }
      };
      
      {
        val __value = parallel
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(11, __value)
        }
      };
      
      {
        val __value = monitorEndpoint
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(12, __value)
        }
      };
      
      {
        val __value = organization
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(14, __value)
        }
      };
      if (sourcePosition.isDefined) {
        val __value = sourcePosition.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = tok
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      args.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      argDependencies.foreach { __v =>
        val __m = pulumirpc.provider.CallRequest._typemapper_argDependencies.toBase(__v)
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = provider
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = version
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = project
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      {
        val __v = stack
        if (!__v.isEmpty) {
          _output__.writeString(7, __v)
        }
      };
      config.foreach { __v =>
        val __m = pulumirpc.provider.CallRequest._typemapper_config.toBase(__v)
        _output__.writeTag(8, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      configSecretKeys.foreach { __v =>
        val __m = __v
        _output__.writeString(9, __m)
      };
      {
        val __v = dryRun
        if (__v != false) {
          _output__.writeBool(10, __v)
        }
      };
      {
        val __v = parallel
        if (__v != 0) {
          _output__.writeInt32(11, __v)
        }
      };
      {
        val __v = monitorEndpoint
        if (!__v.isEmpty) {
          _output__.writeString(12, __v)
        }
      };
      {
        val __v = pluginDownloadURL
        if (!__v.isEmpty) {
          _output__.writeString(13, __v)
        }
      };
      {
        val __v = organization
        if (!__v.isEmpty) {
          _output__.writeString(14, __v)
        }
      };
      sourcePosition.foreach { __v =>
        val __m = __v
        _output__.writeTag(15, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      pluginChecksums.foreach { __v =>
        val __m = pulumirpc.provider.CallRequest._typemapper_pluginChecksums.toBase(__v)
        _output__.writeTag(16, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withTok(__v: _root_.scala.Predef.String): CallRequest = copy(tok = __v)
    def getArgs: com.google.protobuf.struct.Struct = args.getOrElse(com.google.protobuf.struct.Struct.defaultInstance)
    def clearArgs: CallRequest = copy(args = _root_.scala.None)
    def withArgs(__v: com.google.protobuf.struct.Struct): CallRequest = copy(args = Option(__v))
    def clearArgDependencies = copy(argDependencies = _root_.scala.collection.immutable.Map.empty)
    def addArgDependencies(__vs: (_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies) *): CallRequest = addAllArgDependencies(__vs)
    def addAllArgDependencies(__vs: Iterable[(_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies)]): CallRequest = copy(argDependencies = argDependencies ++ __vs)
    def withArgDependencies(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies]): CallRequest = copy(argDependencies = __v)
    def withProvider(__v: _root_.scala.Predef.String): CallRequest = copy(provider = __v)
    def withVersion(__v: _root_.scala.Predef.String): CallRequest = copy(version = __v)
    def withPluginDownloadURL(__v: _root_.scala.Predef.String): CallRequest = copy(pluginDownloadURL = __v)
    def clearPluginChecksums = copy(pluginChecksums = _root_.scala.collection.immutable.Map.empty)
    def addPluginChecksums(__vs: (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString) *): CallRequest = addAllPluginChecksums(__vs)
    def addAllPluginChecksums(__vs: Iterable[(_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]): CallRequest = copy(pluginChecksums = pluginChecksums ++ __vs)
    def withPluginChecksums(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]): CallRequest = copy(pluginChecksums = __v)
    def withProject(__v: _root_.scala.Predef.String): CallRequest = copy(project = __v)
    def withStack(__v: _root_.scala.Predef.String): CallRequest = copy(stack = __v)
    def clearConfig = copy(config = _root_.scala.collection.immutable.Map.empty)
    def addConfig(__vs: (_root_.scala.Predef.String, _root_.scala.Predef.String) *): CallRequest = addAllConfig(__vs)
    def addAllConfig(__vs: Iterable[(_root_.scala.Predef.String, _root_.scala.Predef.String)]): CallRequest = copy(config = config ++ __vs)
    def withConfig(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.scala.Predef.String]): CallRequest = copy(config = __v)
    def clearConfigSecretKeys = copy(configSecretKeys = _root_.scala.Seq.empty)
    def addConfigSecretKeys(__vs: _root_.scala.Predef.String *): CallRequest = addAllConfigSecretKeys(__vs)
    def addAllConfigSecretKeys(__vs: Iterable[_root_.scala.Predef.String]): CallRequest = copy(configSecretKeys = configSecretKeys ++ __vs)
    def withConfigSecretKeys(__v: _root_.scala.Seq[_root_.scala.Predef.String]): CallRequest = copy(configSecretKeys = __v)
    def withDryRun(__v: _root_.scala.Boolean): CallRequest = copy(dryRun = __v)
    def withParallel(__v: _root_.scala.Int): CallRequest = copy(parallel = __v)
    def withMonitorEndpoint(__v: _root_.scala.Predef.String): CallRequest = copy(monitorEndpoint = __v)
    def withOrganization(__v: _root_.scala.Predef.String): CallRequest = copy(organization = __v)
    def getSourcePosition: pulumirpc.source.SourcePosition = sourcePosition.getOrElse(pulumirpc.source.SourcePosition.defaultInstance)
    def clearSourcePosition: CallRequest = copy(sourcePosition = _root_.scala.None)
    def withSourcePosition(__v: pulumirpc.source.SourcePosition): CallRequest = copy(sourcePosition = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = tok
          if (__t != "") __t else null
        }
        case 2 => args.orNull
        case 3 => argDependencies.iterator.map(pulumirpc.provider.CallRequest._typemapper_argDependencies.toBase(_)).toSeq
        case 4 => {
          val __t = provider
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = version
          if (__t != "") __t else null
        }
        case 13 => {
          val __t = pluginDownloadURL
          if (__t != "") __t else null
        }
        case 16 => pluginChecksums.iterator.map(pulumirpc.provider.CallRequest._typemapper_pluginChecksums.toBase(_)).toSeq
        case 6 => {
          val __t = project
          if (__t != "") __t else null
        }
        case 7 => {
          val __t = stack
          if (__t != "") __t else null
        }
        case 8 => config.iterator.map(pulumirpc.provider.CallRequest._typemapper_config.toBase(_)).toSeq
        case 9 => configSecretKeys
        case 10 => {
          val __t = dryRun
          if (__t != false) __t else null
        }
        case 11 => {
          val __t = parallel
          if (__t != 0) __t else null
        }
        case 12 => {
          val __t = monitorEndpoint
          if (__t != "") __t else null
        }
        case 14 => {
          val __t = organization
          if (__t != "") __t else null
        }
        case 15 => sourcePosition.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(tok)
        case 2 => args.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => _root_.scalapb.descriptors.PRepeated(argDependencies.iterator.map(pulumirpc.provider.CallRequest._typemapper_argDependencies.toBase(_).toPMessage).toVector)
        case 4 => _root_.scalapb.descriptors.PString(provider)
        case 5 => _root_.scalapb.descriptors.PString(version)
        case 13 => _root_.scalapb.descriptors.PString(pluginDownloadURL)
        case 16 => _root_.scalapb.descriptors.PRepeated(pluginChecksums.iterator.map(pulumirpc.provider.CallRequest._typemapper_pluginChecksums.toBase(_).toPMessage).toVector)
        case 6 => _root_.scalapb.descriptors.PString(project)
        case 7 => _root_.scalapb.descriptors.PString(stack)
        case 8 => _root_.scalapb.descriptors.PRepeated(config.iterator.map(pulumirpc.provider.CallRequest._typemapper_config.toBase(_).toPMessage).toVector)
        case 9 => _root_.scalapb.descriptors.PRepeated(configSecretKeys.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
        case 10 => _root_.scalapb.descriptors.PBoolean(dryRun)
        case 11 => _root_.scalapb.descriptors.PInt(parallel)
        case 12 => _root_.scalapb.descriptors.PString(monitorEndpoint)
        case 14 => _root_.scalapb.descriptors.PString(organization)
        case 15 => sourcePosition.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: pulumirpc.provider.CallRequest.type = pulumirpc.provider.CallRequest
    // @@protoc_insertion_point(GeneratedMessage[pulumirpc.CallRequest])
}

object CallRequest extends scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.provider.CallRequest = {
    var __tok: _root_.scala.Predef.String = ""
    var __args: _root_.scala.Option[com.google.protobuf.struct.Struct] = _root_.scala.None
    val __argDependencies: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies]
    var __provider: _root_.scala.Predef.String = ""
    var __version: _root_.scala.Predef.String = ""
    var __pluginDownloadURL: _root_.scala.Predef.String = ""
    val __pluginChecksums: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]
    var __project: _root_.scala.Predef.String = ""
    var __stack: _root_.scala.Predef.String = ""
    val __config: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, _root_.scala.Predef.String), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.scala.Predef.String]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, _root_.scala.Predef.String]
    val __configSecretKeys: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    var __dryRun: _root_.scala.Boolean = false
    var __parallel: _root_.scala.Int = 0
    var __monitorEndpoint: _root_.scala.Predef.String = ""
    var __organization: _root_.scala.Predef.String = ""
    var __sourcePosition: _root_.scala.Option[pulumirpc.source.SourcePosition] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __tok = _input__.readStringRequireUtf8()
        case 18 =>
          __args = Option(__args.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.struct.Struct](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __argDependencies += pulumirpc.provider.CallRequest._typemapper_argDependencies.toCustom(_root_.scalapb.LiteParser.readMessage[pulumirpc.provider.CallRequest.ArgDependenciesEntry](_input__))
        case 34 =>
          __provider = _input__.readStringRequireUtf8()
        case 42 =>
          __version = _input__.readStringRequireUtf8()
        case 106 =>
          __pluginDownloadURL = _input__.readStringRequireUtf8()
        case 130 =>
          __pluginChecksums += pulumirpc.provider.CallRequest._typemapper_pluginChecksums.toCustom(_root_.scalapb.LiteParser.readMessage[pulumirpc.provider.CallRequest.PluginChecksumsEntry](_input__))
        case 50 =>
          __project = _input__.readStringRequireUtf8()
        case 58 =>
          __stack = _input__.readStringRequireUtf8()
        case 66 =>
          __config += pulumirpc.provider.CallRequest._typemapper_config.toCustom(_root_.scalapb.LiteParser.readMessage[pulumirpc.provider.CallRequest.ConfigEntry](_input__))
        case 74 =>
          __configSecretKeys += _input__.readStringRequireUtf8()
        case 80 =>
          __dryRun = _input__.readBool()
        case 88 =>
          __parallel = _input__.readInt32()
        case 98 =>
          __monitorEndpoint = _input__.readStringRequireUtf8()
        case 114 =>
          __organization = _input__.readStringRequireUtf8()
        case 122 =>
          __sourcePosition = Option(__sourcePosition.fold(_root_.scalapb.LiteParser.readMessage[pulumirpc.source.SourcePosition](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    pulumirpc.provider.CallRequest(
        tok = __tok,
        args = __args,
        argDependencies = __argDependencies.result(),
        provider = __provider,
        version = __version,
        pluginDownloadURL = __pluginDownloadURL,
        pluginChecksums = __pluginChecksums.result(),
        project = __project,
        stack = __stack,
        config = __config.result(),
        configSecretKeys = __configSecretKeys.result(),
        dryRun = __dryRun,
        parallel = __parallel,
        monitorEndpoint = __monitorEndpoint,
        organization = __organization,
        sourcePosition = __sourcePosition,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.provider.CallRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      pulumirpc.provider.CallRequest(
        tok = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        args = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[com.google.protobuf.struct.Struct]]),
        argDependencies = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[pulumirpc.provider.CallRequest.ArgDependenciesEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(pulumirpc.provider.CallRequest._typemapper_argDependencies.toCustom(_)).toMap,
        provider = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        pluginDownloadURL = __fieldsMap.get(scalaDescriptor.findFieldByNumber(13).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        pluginChecksums = __fieldsMap.get(scalaDescriptor.findFieldByNumber(16).get).map(_.as[_root_.scala.Seq[pulumirpc.provider.CallRequest.PluginChecksumsEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(pulumirpc.provider.CallRequest._typemapper_pluginChecksums.toCustom(_)).toMap,
        project = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        stack = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        config = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Seq[pulumirpc.provider.CallRequest.ConfigEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(pulumirpc.provider.CallRequest._typemapper_config.toCustom(_)).toMap,
        configSecretKeys = __fieldsMap.get(scalaDescriptor.findFieldByNumber(9).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty),
        dryRun = __fieldsMap.get(scalaDescriptor.findFieldByNumber(10).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        parallel = __fieldsMap.get(scalaDescriptor.findFieldByNumber(11).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        monitorEndpoint = __fieldsMap.get(scalaDescriptor.findFieldByNumber(12).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        organization = __fieldsMap.get(scalaDescriptor.findFieldByNumber(14).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        sourcePosition = __fieldsMap.get(scalaDescriptor.findFieldByNumber(15).get).flatMap(_.as[_root_.scala.Option[pulumirpc.source.SourcePosition]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ProviderProto.javaDescriptor.getMessageTypes().get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ProviderProto.scalaDescriptor.messages(7)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = com.google.protobuf.struct.Struct
      case 3 => __out = pulumirpc.provider.CallRequest.ArgDependenciesEntry
      case 16 => __out = pulumirpc.provider.CallRequest.PluginChecksumsEntry
      case 8 => __out = pulumirpc.provider.CallRequest.ConfigEntry
      case 15 => __out = pulumirpc.source.SourcePosition
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.pulumirpc.provider.CallRequest.ArgumentDependencies,
      _root_.pulumirpc.provider.CallRequest.ArgDependenciesEntry,
      _root_.pulumirpc.provider.CallRequest.PluginChecksumsEntry,
      _root_.pulumirpc.provider.CallRequest.ConfigEntry
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = pulumirpc.provider.CallRequest(
    tok = "",
    args = _root_.scala.None,
    argDependencies = _root_.scala.collection.immutable.Map.empty,
    provider = "",
    version = "",
    pluginDownloadURL = "",
    pluginChecksums = _root_.scala.collection.immutable.Map.empty,
    project = "",
    stack = "",
    config = _root_.scala.collection.immutable.Map.empty,
    configSecretKeys = _root_.scala.Seq.empty,
    dryRun = false,
    parallel = 0,
    monitorEndpoint = "",
    organization = "",
    sourcePosition = _root_.scala.None
  )
  /** ArgumentDependencies describes the resources that a particular argument depends on.
    *
    * @param urns
    *   A list of URNs this argument depends on.
    */
  @SerialVersionUID(0L)
  final case class ArgumentDependencies(
      urns: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ArgumentDependencies] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        urns.foreach { __item =>
          val __value = __item
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        urns.foreach { __v =>
          val __m = __v
          _output__.writeString(1, __m)
        };
        unknownFields.writeTo(_output__)
      }
      def clearUrns = copy(urns = _root_.scala.Seq.empty)
      def addUrns(__vs: _root_.scala.Predef.String *): ArgumentDependencies = addAllUrns(__vs)
      def addAllUrns(__vs: Iterable[_root_.scala.Predef.String]): ArgumentDependencies = copy(urns = urns ++ __vs)
      def withUrns(__v: _root_.scala.Seq[_root_.scala.Predef.String]): ArgumentDependencies = copy(urns = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => urns
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PRepeated(urns.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: pulumirpc.provider.CallRequest.ArgumentDependencies.type = pulumirpc.provider.CallRequest.ArgumentDependencies
      // @@protoc_insertion_point(GeneratedMessage[pulumirpc.CallRequest.ArgumentDependencies])
  }
  
  object ArgumentDependencies extends scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest.ArgumentDependencies] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest.ArgumentDependencies] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.provider.CallRequest.ArgumentDependencies = {
      val __urns: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __urns += _input__.readStringRequireUtf8()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      pulumirpc.provider.CallRequest.ArgumentDependencies(
          urns = __urns.result(),
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.provider.CallRequest.ArgumentDependencies] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        pulumirpc.provider.CallRequest.ArgumentDependencies(
          urns = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = pulumirpc.provider.CallRequest.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = pulumirpc.provider.CallRequest.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = pulumirpc.provider.CallRequest.ArgumentDependencies(
      urns = _root_.scala.Seq.empty
    )
    implicit class ArgumentDependenciesLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.provider.CallRequest.ArgumentDependencies]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, pulumirpc.provider.CallRequest.ArgumentDependencies](_l) {
      def urns: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.urns)((c_, f_) => c_.copy(urns = f_))
    }
    final val URNS_FIELD_NUMBER = 1
    def of(
      urns: _root_.scala.Seq[_root_.scala.Predef.String]
    ): _root_.pulumirpc.provider.CallRequest.ArgumentDependencies = _root_.pulumirpc.provider.CallRequest.ArgumentDependencies(
      urns
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.CallRequest.ArgumentDependencies])
  }
  
  @SerialVersionUID(0L)
  final case class ArgDependenciesEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.scala.Option[pulumirpc.provider.CallRequest.ArgumentDependencies] = _root_.scala.None,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ArgDependenciesEntry] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        if (value.isDefined) {
          val __value = value.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          val __m = __v
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        unknownFields.writeTo(_output__)
      }
      def withKey(__v: _root_.scala.Predef.String): ArgDependenciesEntry = copy(key = __v)
      def getValue: pulumirpc.provider.CallRequest.ArgumentDependencies = value.getOrElse(pulumirpc.provider.CallRequest.ArgumentDependencies.defaultInstance)
      def clearValue: ArgDependenciesEntry = copy(value = _root_.scala.None)
      def withValue(__v: pulumirpc.provider.CallRequest.ArgumentDependencies): ArgDependenciesEntry = copy(value = Option(__v))
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: pulumirpc.provider.CallRequest.ArgDependenciesEntry.type = pulumirpc.provider.CallRequest.ArgDependenciesEntry
      // @@protoc_insertion_point(GeneratedMessage[pulumirpc.CallRequest.ArgDependenciesEntry])
  }
  
  object ArgDependenciesEntry extends scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest.ArgDependenciesEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest.ArgDependenciesEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.provider.CallRequest.ArgDependenciesEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.scala.Option[pulumirpc.provider.CallRequest.ArgumentDependencies] = _root_.scala.None
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = Option(__value.fold(_root_.scalapb.LiteParser.readMessage[pulumirpc.provider.CallRequest.ArgumentDependencies](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      pulumirpc.provider.CallRequest.ArgDependenciesEntry(
          key = __key,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.provider.CallRequest.ArgDependenciesEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        pulumirpc.provider.CallRequest.ArgDependenciesEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[pulumirpc.provider.CallRequest.ArgumentDependencies]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = pulumirpc.provider.CallRequest.javaDescriptor.getNestedTypes().get(1)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = pulumirpc.provider.CallRequest.scalaDescriptor.nestedMessages(1)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = pulumirpc.provider.CallRequest.ArgumentDependencies
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = pulumirpc.provider.CallRequest.ArgDependenciesEntry(
      key = "",
      value = _root_.scala.None
    )
    implicit class ArgDependenciesEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.provider.CallRequest.ArgDependenciesEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, pulumirpc.provider.CallRequest.ArgDependenciesEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.provider.CallRequest.ArgumentDependencies] = field(_.getValue)((c_, f_) => c_.copy(value = Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[pulumirpc.provider.CallRequest.ArgumentDependencies]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.ArgDependenciesEntry, (_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies)] =
      _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.ArgDependenciesEntry, (_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies)](__m => (__m.key, __m.getValue))(__p => pulumirpc.provider.CallRequest.ArgDependenciesEntry(__p._1, Some(__p._2)))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.scala.Option[pulumirpc.provider.CallRequest.ArgumentDependencies]
    ): _root_.pulumirpc.provider.CallRequest.ArgDependenciesEntry = _root_.pulumirpc.provider.CallRequest.ArgDependenciesEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.CallRequest.ArgDependenciesEntry])
  }
  
  @SerialVersionUID(0L)
  final case class PluginChecksumsEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[PluginChecksumsEntry] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = value
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = value
          if (!__v.isEmpty) {
            _output__.writeBytes(2, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def withKey(__v: _root_.scala.Predef.String): PluginChecksumsEntry = copy(key = __v)
      def withValue(__v: _root_.com.google.protobuf.ByteString): PluginChecksumsEntry = copy(value = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = value
            if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => _root_.scalapb.descriptors.PByteString(value)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: pulumirpc.provider.CallRequest.PluginChecksumsEntry.type = pulumirpc.provider.CallRequest.PluginChecksumsEntry
      // @@protoc_insertion_point(GeneratedMessage[pulumirpc.CallRequest.PluginChecksumsEntry])
  }
  
  object PluginChecksumsEntry extends scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest.PluginChecksumsEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest.PluginChecksumsEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.provider.CallRequest.PluginChecksumsEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = _input__.readBytes()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      pulumirpc.provider.CallRequest.PluginChecksumsEntry(
          key = __key,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.provider.CallRequest.PluginChecksumsEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        pulumirpc.provider.CallRequest.PluginChecksumsEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = pulumirpc.provider.CallRequest.javaDescriptor.getNestedTypes().get(2)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = pulumirpc.provider.CallRequest.scalaDescriptor.nestedMessages(2)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = pulumirpc.provider.CallRequest.PluginChecksumsEntry(
      key = "",
      value = _root_.com.google.protobuf.ByteString.EMPTY
    )
    implicit class PluginChecksumsEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.provider.CallRequest.PluginChecksumsEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, pulumirpc.provider.CallRequest.PluginChecksumsEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.PluginChecksumsEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] =
      _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.PluginChecksumsEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)](__m => (__m.key, __m.value))(__p => pulumirpc.provider.CallRequest.PluginChecksumsEntry(__p._1, __p._2))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.com.google.protobuf.ByteString
    ): _root_.pulumirpc.provider.CallRequest.PluginChecksumsEntry = _root_.pulumirpc.provider.CallRequest.PluginChecksumsEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.CallRequest.PluginChecksumsEntry])
  }
  
  @SerialVersionUID(0L)
  final case class ConfigEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.scala.Predef.String = "",
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ConfigEntry] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = value
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = value
          if (!__v.isEmpty) {
            _output__.writeString(2, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def withKey(__v: _root_.scala.Predef.String): ConfigEntry = copy(key = __v)
      def withValue(__v: _root_.scala.Predef.String): ConfigEntry = copy(value = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = value
            if (__t != "") __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => _root_.scalapb.descriptors.PString(value)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: pulumirpc.provider.CallRequest.ConfigEntry.type = pulumirpc.provider.CallRequest.ConfigEntry
      // @@protoc_insertion_point(GeneratedMessage[pulumirpc.CallRequest.ConfigEntry])
  }
  
  object ConfigEntry extends scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest.ConfigEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.provider.CallRequest.ConfigEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.provider.CallRequest.ConfigEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.scala.Predef.String = ""
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = _input__.readStringRequireUtf8()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      pulumirpc.provider.CallRequest.ConfigEntry(
          key = __key,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.provider.CallRequest.ConfigEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        pulumirpc.provider.CallRequest.ConfigEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = pulumirpc.provider.CallRequest.javaDescriptor.getNestedTypes().get(3)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = pulumirpc.provider.CallRequest.scalaDescriptor.nestedMessages(3)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = pulumirpc.provider.CallRequest.ConfigEntry(
      key = "",
      value = ""
    )
    implicit class ConfigEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.provider.CallRequest.ConfigEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, pulumirpc.provider.CallRequest.ConfigEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.ConfigEntry, (_root_.scala.Predef.String, _root_.scala.Predef.String)] =
      _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.ConfigEntry, (_root_.scala.Predef.String, _root_.scala.Predef.String)](__m => (__m.key, __m.value))(__p => pulumirpc.provider.CallRequest.ConfigEntry(__p._1, __p._2))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.scala.Predef.String
    ): _root_.pulumirpc.provider.CallRequest.ConfigEntry = _root_.pulumirpc.provider.CallRequest.ConfigEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.CallRequest.ConfigEntry])
  }
  
  implicit class CallRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.provider.CallRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, pulumirpc.provider.CallRequest](_l) {
    def tok: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.tok)((c_, f_) => c_.copy(tok = f_))
    def args: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.struct.Struct] = field(_.getArgs)((c_, f_) => c_.copy(args = Option(f_)))
    def optionalArgs: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[com.google.protobuf.struct.Struct]] = field(_.args)((c_, f_) => c_.copy(args = f_))
    def argDependencies: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies]] = field(_.argDependencies)((c_, f_) => c_.copy(argDependencies = f_))
    def provider: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.provider)((c_, f_) => c_.copy(provider = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
    def pluginDownloadURL: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.pluginDownloadURL)((c_, f_) => c_.copy(pluginDownloadURL = f_))
    def pluginChecksums: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]] = field(_.pluginChecksums)((c_, f_) => c_.copy(pluginChecksums = f_))
    def project: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.project)((c_, f_) => c_.copy(project = f_))
    def stack: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.stack)((c_, f_) => c_.copy(stack = f_))
    def config: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.scala.Predef.String]] = field(_.config)((c_, f_) => c_.copy(config = f_))
    def configSecretKeys: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.configSecretKeys)((c_, f_) => c_.copy(configSecretKeys = f_))
    def dryRun: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.dryRun)((c_, f_) => c_.copy(dryRun = f_))
    def parallel: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.parallel)((c_, f_) => c_.copy(parallel = f_))
    def monitorEndpoint: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.monitorEndpoint)((c_, f_) => c_.copy(monitorEndpoint = f_))
    def organization: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.organization)((c_, f_) => c_.copy(organization = f_))
    def sourcePosition: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.source.SourcePosition] = field(_.getSourcePosition)((c_, f_) => c_.copy(sourcePosition = Option(f_)))
    def optionalSourcePosition: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[pulumirpc.source.SourcePosition]] = field(_.sourcePosition)((c_, f_) => c_.copy(sourcePosition = f_))
  }
  final val TOK_FIELD_NUMBER = 1
  final val ARGS_FIELD_NUMBER = 2
  final val ARGDEPENDENCIES_FIELD_NUMBER = 3
  final val PROVIDER_FIELD_NUMBER = 4
  final val VERSION_FIELD_NUMBER = 5
  final val PLUGINDOWNLOADURL_FIELD_NUMBER = 13
  final val PLUGINCHECKSUMS_FIELD_NUMBER = 16
  final val PROJECT_FIELD_NUMBER = 6
  final val STACK_FIELD_NUMBER = 7
  final val CONFIG_FIELD_NUMBER = 8
  final val CONFIGSECRETKEYS_FIELD_NUMBER = 9
  final val DRYRUN_FIELD_NUMBER = 10
  final val PARALLEL_FIELD_NUMBER = 11
  final val MONITORENDPOINT_FIELD_NUMBER = 12
  final val ORGANIZATION_FIELD_NUMBER = 14
  final val SOURCEPOSITION_FIELD_NUMBER = 15
  @transient
  private[provider] val _typemapper_argDependencies: _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.ArgDependenciesEntry, (_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies)] = implicitly[_root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.ArgDependenciesEntry, (_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies)]]
  @transient
  private[provider] val _typemapper_pluginChecksums: _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.PluginChecksumsEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] = implicitly[_root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.PluginChecksumsEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]]
  @transient
  private[provider] val _typemapper_config: _root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.ConfigEntry, (_root_.scala.Predef.String, _root_.scala.Predef.String)] = implicitly[_root_.scalapb.TypeMapper[pulumirpc.provider.CallRequest.ConfigEntry, (_root_.scala.Predef.String, _root_.scala.Predef.String)]]
  def of(
    tok: _root_.scala.Predef.String,
    args: _root_.scala.Option[com.google.protobuf.struct.Struct],
    argDependencies: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, pulumirpc.provider.CallRequest.ArgumentDependencies],
    provider: _root_.scala.Predef.String,
    version: _root_.scala.Predef.String,
    pluginDownloadURL: _root_.scala.Predef.String,
    pluginChecksums: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString],
    project: _root_.scala.Predef.String,
    stack: _root_.scala.Predef.String,
    config: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.scala.Predef.String],
    configSecretKeys: _root_.scala.Seq[_root_.scala.Predef.String],
    dryRun: _root_.scala.Boolean,
    parallel: _root_.scala.Int,
    monitorEndpoint: _root_.scala.Predef.String,
    organization: _root_.scala.Predef.String,
    sourcePosition: _root_.scala.Option[pulumirpc.source.SourcePosition]
  ): _root_.pulumirpc.provider.CallRequest = _root_.pulumirpc.provider.CallRequest(
    tok,
    args,
    argDependencies,
    provider,
    version,
    pluginDownloadURL,
    pluginChecksums,
    project,
    stack,
    config,
    configSecretKeys,
    dryRun,
    parallel,
    monitorEndpoint,
    organization,
    sourcePosition
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.CallRequest])
}
