//> using scala "2.13.10"
//> using lib "org.scalameta::scalameta:4.8.10"
//> using lib "com.lihaoyi::upickle:3.1.3"
//> using lib "com.lihaoyi::os-lib:0.9.1"

//> using publish.name "besom-codegen"
//> using publish.organization "org.virtuslab"
//> using publish.url "https://github.com/VirtusLab/besom"
//> using publish.vcs "github:VirtusLab/besom"
//> using publish.license "Apache-2.0"
//> using publish.repository "central"
//> using publish.developer "lbialy|Łukasz Biały|https://github.com/lbialy"
//> using publish.developer "prolativ|Michał Pałka|https://github.com/prolativ"
//> using publish.developer "KacperFKorban|Kacper Korban|https://github.com/KacperFKorban"