//> using scala "3.3.0"
//> using plugin "org.virtuslab::besom-compiler-plugin:0.0.2-SNAPSHOT"
//> using dep "org.virtuslab::besom-core:0.0.2-SNAPSHOT"
//> using dep "org.virtuslab::besom-kubernetes:4.2.0-core.0.0.2-SNAPSHOT"
//> using dep "io.github.iltotore::iron:2.1.0"
