//> using scala "3.3.0"
//> using plugin "org.virtuslab::besom-compiler-plugin:0.0.1-SNAPSHOT"
//> using dep "org.virtuslab::besom-core:4.13.2-SNAPSHOT.0.0.1"
//> using dep "org.virtuslab::besom-kubernetes:4.1.1-SNAPSHOT.0.0.1"
//> using dep "io.github.iltotore::iron:2.1.0"