//> using scala "3.3.1"
//> using options "-java-output-version:11", "-Ykind-projector:underscores"
//> using options "-deprecation", "-feature"

//> using dep "org.virtuslab::besom-core:0.3.2"
//> using dep "org.typelevel::cats-effect:3.3.14"
//> using test.dep "org.scalameta::munit:1.0.0-M10"

//> using publish.name "besom-cats"
//> using publish.organization "org.virtuslab"
//> using publish.url "https://github.com/VirtusLab/besom"
//> using publish.vcs "github:VirtusLab/besom"
//> using publish.license "Apache-2.0"
//> using publish.repository "central"
//> using publish.developer "lbialy|Łukasz Biały|https://github.com/lbialy"
//> using publish.developer "prolativ|Michał Pałka|https://github.com/prolativ"
//> using publish.developer "KacperFKorban|Kacper Korban|https://github.com/KacperFKorban"
