// Copyright 2022, Pulumi Corporation.  All rights reserved.

package executors

import (
	"fmt"
	"os"
	"io"
	"path/filepath"
	"strings"

	"github.com/virtuslab/besom/language-host/fsys"
)

type sbt struct{}

var _ scalaExecutorFactory = &sbt{}

func (s sbt) NewScalaExecutor(opts ScalaExecutorOptions) (*ScalaExecutor, error) {
	ok, err := s.isSbtProject(opts)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	probePaths := []string{opts.UseExecutor}
	if opts.UseExecutor == "" {
		probePaths = []string{"./sbt", "sbt"}
	}
	cmd, err := fsys.LookPath(opts.WD, probePaths...)
	if err != nil {
		return nil, err
	}
	return s.newSbtExecutor(cmd, opts.WD, opts.LanguagePluginHomeDir)
}

func (sbt) isSbtProject(opts ScalaExecutorOptions) (bool, error) {
	if strings.Contains(opts.UseExecutor, "sbt") {
		return true, nil
	}
	sbtMarkers := []string{
		"project/build.properties",
		"build.sbt",
	}
	for _, p := range sbtMarkers {
		isSbt, err := fsys.FileExists(opts.WD, p)
		if err != nil {
			return false, err
		}
		if isSbt {
			return true, nil
		}
	}
	return false, nil
}

// sbtBesomPluginFiles describes where each shipped source file has to land in the user's project.
// sbt builds its meta-build (the `project` directory) with Scala 2.12 on the sbt 1.x line and with
// Scala 3 on the sbt 2.x line, and only reads the cross-version source directory matching that
// binary version. Dropping both variants therefore lets a single language plugin release serve both
// sbt lines without having to detect the sbt version: whichever sbt the user runs compiles exactly
// one of them and ignores the other. The shared base goes to the plain `scala` directory, which both
// lines compile.
var sbtBesomPluginFiles = []struct {
	// Subdirectory of the language plugin home dir holding the file.
	variant string
	// File name, the same on both sides of the copy.
	fileName string
	// Source directory under project/src/main the file is written to.
	scalaSourceDir string
}{
	{variant: "shared", fileName: "BesomPluginBase.scala", scalaSourceDir: "scala"},
	{variant: "sbt1", fileName: "BesomPlugin.scala", scalaSourceDir: "scala-2.12"},
	{variant: "sbt2", fileName: "BesomPlugin.scala", scalaSourceDir: "scala-3"},
}

// besomPluginGeneratedMarker appears in the header of every BesomPlugin.scala besom writes out.
const besomPluginGeneratedMarker = "This file was generated by besom"

func (sbt) newSbtExecutor(cmd string, projectRoot fsys.ParentFS, languagePluginHomeDir string) (*ScalaExecutor, error) {
	sbtModule := os.Getenv("BESOM_SBT_MODULE")
	bootstrapLibJarPath := ResolveBootstrapLibJarPath(languagePluginHomeDir)
	pluginDiscovererOutputPath := PluginDiscovererOutputFilePath(projectRoot)

	se := &ScalaExecutor{
		Name:       "sbt",
		Cmd:        cmd,
		RunArgs:    makeArgs(sbtModule, "run"),
		BuildArgs:  makeArgs(sbtModule, "compile"),
		PluginArgs: makeArgs(sbtModule, fmt.Sprintf(`besomExtractPulumiPlugins %s %s`, bootstrapLibJarPath, pluginDiscovererOutputPath)),
		// --script-version is understood by both the sbt 1.x and the sbt 2.x runner script.
		// --numeric-version is sbt 1.x only; sbt 2.x ignores it and drops into an interactive shell.
		VersionArgs: []string{"--script-version"},
		SetupProject: func() error {
			if err := removeLegacyBesomPlugin(projectRoot); err != nil {
				return err
			}
			for _, f := range sbtBesomPluginFiles {
				srcPath := SbtBesomPluginPath(languagePluginHomeDir, f.variant, f.fileName)
				destPath := filepath.Join(projectRoot.Path(), "project", "src", "main", f.scalaSourceDir, f.fileName)
				if err := copyFileIfNotPresent(srcPath, destPath); err != nil {
					return err
				}
			}
			return nil
		},
	}

	return se, nil
}

// removeLegacyBesomPlugin deletes the project/BesomPlugin.scala that besom versions before
// sbt 2.x support used to write. sbt compiles project/*.scala together with the cross-version
// source directories, so leaving it behind would define BesomPlugin twice and break the
// meta-build. Files the user wrote themselves are left alone.
func removeLegacyBesomPlugin(projectRoot fsys.ParentFS) error {
	legacyPath := filepath.Join(projectRoot.Path(), "project", "BesomPlugin.scala")
	contents, err := os.ReadFile(legacyPath)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("error reading legacy besom sbt plugin at %s: %w", legacyPath, err)
	}
	if !strings.Contains(string(contents), besomPluginGeneratedMarker) {
		return nil
	}
	if err := os.Remove(legacyPath); err != nil {
		return fmt.Errorf("failed to remove legacy besom sbt plugin at %s: %w", legacyPath, err)
	}
	return nil
}

func makeArgs(sbtModule string, cmd string) []string {
	if sbtModule != "" {
		return []string{"-batch", fmt.Sprintf("%s/%s", sbtModule, cmd)}
	}
	return []string{"-batch", cmd}
}


// copyFileIfNotPresent copies a file from src to dest only if dest does not already exist.
// It uses io.Copy and preserves the source file's permissions.
// It also creates parent directories for destPath if they do not exist.
func copyFileIfNotPresent(srcPath, destPath string) error {
    // Check if destination file exists
    if _, err := os.Stat(destPath); err == nil {
        // File already exists
        return nil
    } else if !os.IsNotExist(err) {
        // Some other error occurred when checking
        return fmt.Errorf("error checking destination file: %w", err)
    }

    // Ensure parent directories exist
    destDir := filepath.Dir(destPath)
    if err := os.MkdirAll(destDir, 0755); err != nil {
        return fmt.Errorf("failed to create parent directories: %w", err)
    }

    // Open source file
    srcFile, err := os.Open(srcPath)
    if err != nil {
        return fmt.Errorf("failed to open source file: %w", err)
    }
    defer srcFile.Close()

    // Create destination file
    destFile, err := os.Create(destPath)
    if err != nil {
        return fmt.Errorf("failed to create destination file: %w", err)
    }
    defer func() {
        cerr := destFile.Close()
        if err == nil {
            err = cerr
        }
    }()

    // Copy contents
    if _, err := io.Copy(destFile, srcFile); err != nil {
        return fmt.Errorf("failed to copy file contents: %w", err)
    }

    // Copy file permissions
    srcInfo, err := os.Stat(srcPath)
    if err != nil {
        return fmt.Errorf("failed to get source file info: %w", err)
    }
    if err := os.Chmod(destPath, srcInfo.Mode()); err != nil {
        return fmt.Errorf("failed to set destination file permissions: %w", err)
    }

    return nil
}
