// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package pulumirpc.resource

/** @param name
  *   the plugin name.
  * @param version
  *   the plugin version.
  * @param downloadUrl
  *   the optional plugin download url.
  * @param checksums
  *   the optional plugin checksums.
  * @param parameterization
  *   the optional parameterization for this package.
  */
@SerialVersionUID(0L)
final case class RegisterPackageRequest(
    name: _root_.scala.Predef.String = "",
    version: _root_.scala.Predef.String = "",
    downloadUrl: _root_.scala.Predef.String = "",
    checksums: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString] = _root_.scala.collection.immutable.Map.empty,
    parameterization: _root_.scala.Option[pulumirpc.resource.Parameterization] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[RegisterPackageRequest] {
    @transient
    private var __serializedSizeMemoized: _root_.scala.Int = 0
    private def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = version
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = downloadUrl
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      checksums.foreach { __item =>
        val __value = pulumirpc.resource.RegisterPackageRequest._typemapper_checksums.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      if (parameterization.isDefined) {
        val __value = parameterization.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = version
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = downloadUrl
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      checksums.foreach { __v =>
        val __m = pulumirpc.resource.RegisterPackageRequest._typemapper_checksums.toBase(__v)
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      parameterization.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withName(__v: _root_.scala.Predef.String): RegisterPackageRequest = copy(name = __v)
    def withVersion(__v: _root_.scala.Predef.String): RegisterPackageRequest = copy(version = __v)
    def withDownloadUrl(__v: _root_.scala.Predef.String): RegisterPackageRequest = copy(downloadUrl = __v)
    def clearChecksums = copy(checksums = _root_.scala.collection.immutable.Map.empty)
    def addChecksums(__vs: (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString) *): RegisterPackageRequest = addAllChecksums(__vs)
    def addAllChecksums(__vs: Iterable[(_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]): RegisterPackageRequest = copy(checksums = checksums ++ __vs)
    def withChecksums(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]): RegisterPackageRequest = copy(checksums = __v)
    def getParameterization: pulumirpc.resource.Parameterization = parameterization.getOrElse(pulumirpc.resource.Parameterization.defaultInstance)
    def clearParameterization: RegisterPackageRequest = copy(parameterization = _root_.scala.None)
    def withParameterization(__v: pulumirpc.resource.Parameterization): RegisterPackageRequest = copy(parameterization = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = version
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = downloadUrl
          if (__t != "") __t else null
        }
        case 4 => checksums.iterator.map(pulumirpc.resource.RegisterPackageRequest._typemapper_checksums.toBase(_)).toSeq
        case 5 => parameterization.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(name)
        case 2 => _root_.scalapb.descriptors.PString(version)
        case 3 => _root_.scalapb.descriptors.PString(downloadUrl)
        case 4 => _root_.scalapb.descriptors.PRepeated(checksums.iterator.map(pulumirpc.resource.RegisterPackageRequest._typemapper_checksums.toBase(_).toPMessage).toVector)
        case 5 => parameterization.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: pulumirpc.resource.RegisterPackageRequest.type = pulumirpc.resource.RegisterPackageRequest
    // @@protoc_insertion_point(GeneratedMessage[pulumirpc.RegisterPackageRequest])
}

object RegisterPackageRequest extends scalapb.GeneratedMessageCompanion[pulumirpc.resource.RegisterPackageRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.resource.RegisterPackageRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.resource.RegisterPackageRequest = {
    var __name: _root_.scala.Predef.String = ""
    var __version: _root_.scala.Predef.String = ""
    var __downloadUrl: _root_.scala.Predef.String = ""
    val __checksums: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]
    var __parameterization: _root_.scala.Option[pulumirpc.resource.Parameterization] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __name = _input__.readStringRequireUtf8()
        case 18 =>
          __version = _input__.readStringRequireUtf8()
        case 26 =>
          __downloadUrl = _input__.readStringRequireUtf8()
        case 34 =>
          __checksums += pulumirpc.resource.RegisterPackageRequest._typemapper_checksums.toCustom(_root_.scalapb.LiteParser.readMessage[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry](_input__))
        case 42 =>
          __parameterization = _root_.scala.Option(__parameterization.fold(_root_.scalapb.LiteParser.readMessage[pulumirpc.resource.Parameterization](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    pulumirpc.resource.RegisterPackageRequest(
        name = __name,
        version = __version,
        downloadUrl = __downloadUrl,
        checksums = __checksums.result(),
        parameterization = __parameterization,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.resource.RegisterPackageRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      pulumirpc.resource.RegisterPackageRequest(
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        downloadUrl = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        checksums = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(pulumirpc.resource.RegisterPackageRequest._typemapper_checksums.toCustom(_)).toMap,
        parameterization = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[_root_.scala.Option[pulumirpc.resource.Parameterization]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = pulumirpc.resource.ResourceProto.javaDescriptor.getMessageTypes().get(15)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = pulumirpc.resource.ResourceProto.scalaDescriptor.messages(15)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry
      case 5 => __out = pulumirpc.resource.Parameterization
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      _root_.pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = pulumirpc.resource.RegisterPackageRequest(
    name = "",
    version = "",
    downloadUrl = "",
    checksums = _root_.scala.collection.immutable.Map.empty,
    parameterization = _root_.scala.None
  )
  @SerialVersionUID(0L)
  final case class ChecksumsEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ChecksumsEntry] {
      @transient
      private var __serializedSizeMemoized: _root_.scala.Int = 0
      private def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = value
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(2, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = value
          if (!__v.isEmpty) {
            _output__.writeBytes(2, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def withKey(__v: _root_.scala.Predef.String): ChecksumsEntry = copy(key = __v)
      def withValue(__v: _root_.com.google.protobuf.ByteString): ChecksumsEntry = copy(value = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = value
            if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => _root_.scalapb.descriptors.PByteString(value)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry.type = pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry
      // @@protoc_insertion_point(GeneratedMessage[pulumirpc.RegisterPackageRequest.ChecksumsEntry])
  }
  
  object ChecksumsEntry extends scalapb.GeneratedMessageCompanion[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = _input__.readBytes()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry(
          key = __key,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = pulumirpc.resource.RegisterPackageRequest.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = pulumirpc.resource.RegisterPackageRequest.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry(
      key = "",
      value = _root_.com.google.protobuf.ByteString.EMPTY
    )
    implicit class ChecksumsEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry]) extends _root_.scalapb.lenses.MessageLens[UpperPB, pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] =
      _root_.scalapb.TypeMapper[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)](__m => (__m.key, __m.value))(__p => pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry(__p._1, __p._2))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.com.google.protobuf.ByteString
    ): _root_.pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry = _root_.pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.RegisterPackageRequest.ChecksumsEntry])
  }
  
  implicit class RegisterPackageRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.resource.RegisterPackageRequest]) extends _root_.scalapb.lenses.MessageLens[UpperPB, pulumirpc.resource.RegisterPackageRequest](_l) {
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.version)((c_, f_) => c_.copy(version = f_))
    def downloadUrl: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.downloadUrl)((c_, f_) => c_.copy(downloadUrl = f_))
    def checksums: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString]] = field(_.checksums)((c_, f_) => c_.copy(checksums = f_))
    def parameterization: _root_.scalapb.lenses.Lens[UpperPB, pulumirpc.resource.Parameterization] = field(_.getParameterization)((c_, f_) => c_.copy(parameterization = _root_.scala.Option(f_)))
    def optionalParameterization: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[pulumirpc.resource.Parameterization]] = field(_.parameterization)((c_, f_) => c_.copy(parameterization = f_))
  }
  final val NAME_FIELD_NUMBER = 1
  final val VERSION_FIELD_NUMBER = 2
  final val DOWNLOAD_URL_FIELD_NUMBER = 3
  final val CHECKSUMS_FIELD_NUMBER = 4
  final val PARAMETERIZATION_FIELD_NUMBER = 5
  @transient
  private[resource] val _typemapper_checksums: _root_.scalapb.TypeMapper[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)] = implicitly[_root_.scalapb.TypeMapper[pulumirpc.resource.RegisterPackageRequest.ChecksumsEntry, (_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString)]]
  def of(
    name: _root_.scala.Predef.String,
    version: _root_.scala.Predef.String,
    downloadUrl: _root_.scala.Predef.String,
    checksums: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, _root_.com.google.protobuf.ByteString],
    parameterization: _root_.scala.Option[pulumirpc.resource.Parameterization]
  ): _root_.pulumirpc.resource.RegisterPackageRequest = _root_.pulumirpc.resource.RegisterPackageRequest(
    name,
    version,
    downloadUrl,
    checksums,
    parameterization
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[pulumirpc.RegisterPackageRequest])
}
