name: Examples smoke tests

on:
  push:
    branches: [ 'main', 'develop' ]
    paths:
      - 'examples/**'
  pull_request:
    branches: [ 'main', 'develop' ]
    paths:
      - 'examples/**'

env:
  PULUMI_CONFIG_PASSPHRASE: 'passphrase'

jobs:
  preview:
    if: "! github.event.pull_request.head.repo.fork"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
        with:
          just-version: '1.14.0' # just for sanity
      - uses: pulumi/actions@v4
        with:
          pulumi-version: '3.89.0'
      - uses: coursier/cache-action@v6.4.3
      - uses: VirtusLab/scala-cli-setup@v1.0.4
        with:
          jvm: 11
          power: true
      - name: Login in to pulumi
        run: pulumi login --local
      - name: Install language plugin
        run: |- 
          pulumi plugin install language scala --server github://api.github.com/VirtusLab/besom
      - name: Test examples
        env:
          AWS_EC2_METADATA_DISABLED: true
        run: |-
          just test-examples