name: Publish Besom providers to GitHub Packages

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-provider:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        provider:
          - aws
          - azure
          - docker
          - gcp
          - kubernetes
          - random
          - tls
    uses: VirtusLab/besom/.github/workflows/publish-provider.yaml@develop
    with:
      provider: ${{ matrix.provider }}
